%{
01/11/2019
This code is used for to compile all data and match data to strain number in match_data_plot.xlsx.
The code also save 4 final mat files: 
'Straindata_new_0308new.mat': data with 12 replicates 
'Straindata_single_0308.mat':data with only 6 replicates
'Straindata_multi_0308.mat':data with 24 repicates
'Straindata_trip_0308.mat': data with 18 replicates
And plot out all strains with 12 replicates.
%}

clear;clc;

%% create tag vector from excel
dataname = 'match_data_plot.xlsx';
data = xlsread(dataname);
data = data';
vec1 = repelem(data,6,1); % matrix, expr in col, contain 6 replicate for 1 strain in one col
%% create matrix for all data
filename = {
    '1-1.mat'...
    '1-2.mat'...
    '2-1.mat'...
    '2-2.mat'...
    '3-1.mat'...
    '3-2.mat'...
    '4-1.mat'...
    '4-2.mat'...
    '5-1.mat'...
    '5-2.mat'...
    '6-1.mat'....
    '6-2.mat'...
    '7-1.mat'...
    '7-2.mat'...
    '8-1.mat'...
    '8-2.mat'...
    '9-1.mat'...
    '9-2.mat'...
    '10-1.mat'...
    '10-2.mat'...
    '11-1.mat'...
    '11-2.mat'...
    '12-1.mat'...
    '12-2.mat'...
    '13-1.mat'...
    '13-2.mat'...
    '14-1.mat'...
    '14-2.mat'...
    '15-1.mat'...
    '15-2.mat'...
    '16-1.mat'...
    '16-2.mat'...
    '17-1.mat'...
    '17-2.mat'...
    '18-1.mat'...
    '18-2.mat'....
    '19-1.mat'...
    '19-2.mat'...
    '20-1.mat'...
    '20-2.mat'...
    '21-1.mat'...
    '21-2.mat'...
    '22-1.mat'...
    '22-2.mat'...
    '23-1.mat'...
    '23-2.mat'...
    '24-1.mat'...
    '24-2.mat'...
    '25-1.mat'...
    '25-2.mat'...
    '26-1.mat'...
    '26-2.mat'...
    '27-1.mat'...
    '27-2.mat'...
    '28-1.mat'...
    '28-2.mat'...
    '29-1.mat'...
    '29-2.mat'...
    '30-1.mat'...
    '30-2.mat'...
    '32-1.mat'...
    '32-2.mat'...
    '33-1.mat'...
    '33-2.mat'...
    '34-1.mat'...
    '34-2.mat'...
    '35-1.mat'...
    '35-2.mat'...
    '36-1.mat'...
    '36-2.mat'...
    '37-1.mat'...
    '37-2.mat'...
    '38-1.mat'...
    '38-2.mat'...
    '39-1.mat'...
    '39-2.mat'...
    '40-1.mat'...
    '40-2.mat'...
    '41-1.mat'...
    '41-2.mat'...
    '42-1.mat'...
    '42-2.mat'...
    '43-1.mat'...
    '43-2.mat'...
    '44-1.mat'...
    '44-2.mat'...
    '45-1.mat'...
    '45-2.mat'...
    '46-1.mat'...
    '46-2.mat'...
    '47-1.mat'...
    '47-2.mat'...
    '48-1.mat'...
    '48-2.mat'...
    '50-1.mat'...
    '50-2.mat'...
    '51-1.mat'...
    '51-2.mat'...
    '52-1.mat'...
    '52-2.mat'...
    '53-1.mat'...
    '53-2.mat'...
    '54-1.mat'...
    '54-2.mat'...
    '55-1.mat'...
    '55-2.mat'...
    '56-1.mat'...
    '56-2.mat'...
    '57-1.mat'...
    '57-2.mat'...
    '58-1.mat'...
    '58-2.mat'...
    '59-1.mat'...
    '59-2.mat'...
    '60-1.mat'...
    '60-2.mat'...
    '61-1.mat'...
    '61-2.mat'...
    '62-1.mat'...
    '62-2.mat'...
};

N = length(filename); % N = 98
M =[];
Tag = [];
%%
for k = 1:N
    f = filename{k};
    d = load(f);
    dd = d.data; % matrix with observation in row    
    tag = vec1(:,k);
    len = length(tag(~isnan(tag)));
    tag = tag(1:len);
    Tag = [Tag;tag];
    dd = dd(1:len,:);% matrix get rid of empty
    
    D = [tag dd];
    M = [M;D];
end

%% sort the strain numbers
% Note:not all strains have 12 replicates even exclude experiments with
% only 1 Run. There are still data with 4 Runs.

Data = sortrows(M); %all data with tag in row；
Tag = sort(Tag); % all Tag
TT = unique(Tag); % extract unique number in Tag
Tag_num = length(TT); %total strain number
count = []; % count the frequency of each number
Index_single = [];
Index_multi = [];
Index_trip = [];
Data_copy = Data;
Tag_copy = Tag;
ind_1 = [];
ind_2 = [];
ind_3 = [];
for i = 1:Tag_num
    count(i) = sum(Tag == TT(i));
    if count(i) ~= 12 && count(i) ~= 24 && count(i) ~= 18
        ind_1 = find(Data_copy(:,1) == TT(i));
    end
    
    if count(i) == 24
        ind_2 = find(Data_copy(:,1) == TT(i));
    end
    
    if count(i) == 18
        ind_3 = find(Data_copy(:,1) == TT(i));
    end
   
    Index_single = [Index_single;ind_1];
    Index_multi = [Index_multi;ind_2];
    Index_trip = [Index_trip;ind_3];
    ind_1 = [];
    ind_2 = [];
    ind_3 = [];
    
end

Index_single = Index_single';
Index_multi = Index_multi';
Index_trip = Index_trip';
%delete all strain without 12 replicates, and save the data separatly
Straindata_single = Data_copy(Index_single,:);%save single run
Tag_single = Tag_copy(Index_single);

Straindata_multi = Data_copy(Index_multi,:);
Tag_multi = Tag_copy(Index_multi);

Straindata_trip = Data_copy(Index_trip,:);
Tag_trip = Tag_copy(Index_trip);

Data_copy([Index_single,Index_multi, Index_trip],:) = [];%delete single and multi run
Tag_copy([Index_single,Index_multi, Index_trip]) = [];%delete single and multi run tag


TT_copy = unique(Tag_copy);%the tag only have 12 replicates
strain_num = length(TT_copy);%total strain number of 12 replicates

single_copy = unique(Tag_single);
multi_copy = unique(Tag_multi);
trip_copy = unique(Tag_trip);
%% save data with 12 replicates
save('Straindata_new_0308new.mat','Data_copy','Tag_copy','TT_copy','strain_num');
save('Straindata_single_0308.mat','Straindata_single','Tag_single','single_copy');
save('Straindata_multi_0308.mat','Straindata_multi','Tag_multi','multi_copy');
save('Straindata_trip_0308.mat','Straindata_trip','Tag_trip','trip_copy');

%% plot 24 replicates

for k = 1:24
    figure(7);
    subplot(4,6,k);
    plot(Straindata_multi(1+(k-1)*24:k*24-12,2:100)','k');
    hold on;
    plot(Straindata_multi(k*24-11:k*24,2:100)','r');
end

for k = 1:14
    figure(8);
    subplot(3,5,k);
    plot(Straindata_trip(1+(k-1)*18:k*18-12,2:100)','k');
    hold on;
    plot(Straindata_trip(k*18-11:k*18,2:100)','r');
end
    
    
    
% %% plot 12 replicates
% for k = 1:100
%     figure(1);
%     subplot(10,10,k);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end
% % 
% for k = 101:200
%     figure(2);
%     subplot(10,10,k-100);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end 
% 
% for k = 201:300
%     figure(3);
%     subplot(10,10,k-200);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end 
% for k = 301:400
%     figure(4);
%     subplot(10,10,k-300);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end 
% for k = 401:500
%     figure(5);
%     subplot(10,10,k-400);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end 
% for k = 501:600
%     figure(6);
%     subplot(10,10,k-500);
%     plot(Data_copy(1+(k-1)*12:k*12-6,2:100)','k');
%     hold on;
%     plot(Data_copy(k*12-5:k*12,2:100)','r');
%     title(TT_copy(k));
%     xticks([]);
%     ylim([0 0.8]);
% end 
% 
%     
%     
%     
